/* ============================================================
   DAILY DIGEST - LIST DATA
   ------------------------------------------------------------
   This is the ONLY file you edit to add or change lists.
   The engine (index.html) never needs to change.

   HOW TO ADD A LIST: copy one of the blocks below, give it a
   unique `id`, a `name`, a `type`, and its items.

   TYPES:
     "word"  -> definition pulled live from the free Dictionary API
     "wiki"  -> synopsis pulled live from Wikipedia

   WORD LISTS use four buckets (see "lexicon" below):
     simple   : ["word", ...]                weight 1
     weighted : ["word", ...]                weight 2 (repeats in your list)
     groups   : [["form","forms",...], ...]  weight 2, rotates through forms
     noDef    : ["word", ...]                no standard definition; shows a search link

   WIKI LISTS use one bucket `items`, each item:
     { name: "Display name",
       titles: ["Exact Wikipedia Article Title", ...],   // 1+; bundles pull from each
       formula: "KaTeX string" }                          // optional, omit if none
   ============================================================ */

window.APP_LISTS = [

/* ===================== LIST 1: WORDS ===================== */
{
  id: "lexicon",
  name: "Lexicon",
  type: "word",

  // weight 1
  simple: [
    "abortive","abscond","accosted","accusatory","acoustic","adherence",
    "adroitly","aesthetic","affable","affectation","afferent","aggrieved",
    "ahistorical","alacrity","ambit","ambition","amorous","anathema",
    "anatomist","animus","antipathy","apace","aphorism","apropos",
    "ascetic","aspersions","assaying","assent","assuage","assuredly",
    "atrophying","attendant","attenuating","august","aural","auteurs",
    "authenticity","avail","averse","axiomatically","banal","beggars belief",
    "beguile","belying","bereavement","besotted","bohemian","calamity",
    "canard","capex","caustic","chagrin","churlish","clime",
    "cloture","codified","coerce","cogitate","coifed","collate",
    "collegiate","combinatory","commentariat","comparative","compatriots","compel",
    "concatenation","conceit","concentratedly","conciliation","confabulate","confection",
    "conflation","confocal","conformation","congenial","conniving","conscientious",
    "conspiratorial","construe","consummate","contemporaneous","contrapositive","contrition",
    "control-freak","countermand","covenant","creed","crudeness","cudgel",
    "cupidity","dearth","debonaire","decolletage","deign","deleterious",
    "denatures","deportment","derision","determinative","dewar","didactic",
    "diffused","diligently","diminution","diplomatic","disaggregate","discomfit",
    "disparate","disputation","disregard","doctrinal","dubious","duplicative",
    "edematous","efferent","effleurage","effusive","egalitarian","elocution",
    "enigmatic","environs","epithet","equanimity","errant","eschatology",
    "eschew","ethics","etiolated","evinced","exceedance","excoriate",
    "excrescence","excursus","exigencies","exogenous","expedite","expositional",
    "expressly","expropriated","extirpation","extort","extractive","fatuous",
    "faust","feckless","felonious","fiduciary","filial","fillip",
    "fitful","flippant","floridly","frenetic","fusillade","futility",
    "garish","genuflect","gerund","granularity","guise","hallow",
    "hasten","haughty","hellacious","hermetic","homily","iconoclast",
    "idiomatic","idiosyncratic","imbecility","imbibe","imbroglio","imminence",
    "immiserate","immoderate","immured","impecunious","imperious","impetuous",
    "impotence","imprudent","inanity","incandescent","incipient","incorrigible",
    "indefatigably","index","indisposition","induce","inefficacious","ingratiate",
    "injudicious","inoculation","insalubrious","insidious","insolent","intercession",
    "intones","intrenchment","inveighed","inverse","involuntarily","irritant",
    "itinerant","jejune","judiciousness","junta","kafkaesque","kitsch",
    "languidly","lateral","legalese","lexical","libidinous","limerance",
    "linguistic","litany","littoral","lodestar","lothario","luminaries",
    "machinations","magnanimous","malapropism","malefactor","mensch","mercurial",
    "metastasis","meticulous","milia","milieu","mired","misfeasance",
    "modal","modicum","monastic","musings","musters","nadir",
    "nebulous","nefarious","noisome","oblique","omniscient","oppress",
    "opprobrium","ornamentation","ossified","otiose","outmode","palliate",
    "panacea","paragon","parasitic","parcel","parenthetically","parlous",
    "parochial","parsimonious","parvenus","pastiche","pensive","perennial",
    "perfectionist","perforce","perfuse","periphery","pervious","phalanx",
    "phenomenological","philistine","philology","phlegmatic","physiognomy","piquant",
    "pithy","pittance","platitudinous","plenum","pogrom","polemic",
    "polyglot","pontificate","portmanteau","posthumous","praxis","precipitous",
    "preclude","predominate","preponderance","prescience","preternatural","privations",
    "proffered","pronouncements","prosody","provenance","providential","quickened",
    "quintessential","rabbinical","rancorous","rapturous","ravenous","reciprocal",
    "recognizance","recriminations","recumbent","redolent","reductionist","remiss",
    "remit","repertory","replete","repudiate","restive","revolting",
    "rhetorical","riven","ruthless","sagacious","sallow","sapphic",
    "satirize","schadenfreude","scintillation","scorn","screed","scrutiny",
    "sectarian","seminal","sinecure","situate","somatic","sordid",
    "specificity","speculating","staid","stolid","stratagem","stratified",
    "strenuous","strident","subordinated","sufferance","supine","supplement",
    "supplicant","surmise","tacitly","taciturn","tarry","tautological",
    "tete-a-tete","tiresome","tokenistic","torrid","tractable","travails",
    "tristesse","tumescence","ubiquitous","uncouth","undifferentiated","unedifying",
    "unworldly","vassal","vaunted","vesicle","vessel","vestibule",
    "vicissitudes","vociferous","volition","wends"
  ],

  // weight 2 - appeared multiple times in your raw list
  weighted: [
    "abeyance","abrogate","aetiology","ameliorate","anachronistic","apostasy",
    "avarice","begets","capricious","chastened","chicanery","circumspect",
    "cogent","concomitant","contrived","converse","corollary","defenestration",
    "demurred","diatribe","earnestness","enmity","ersatz","extricate",
    "facsimile","febrile","forbearance","forthwith","illustrative","impugn",
    "incredulous","inimitable","iniquity","insipid","interlocutor","intransigence",
    "irascible","largesse","loquacious","malaise","mendacious","obsequious",
    "obstinate","obviate","omnibus","paramour","parity","pejorative",
    "pernicious","phonation","precept","promulgate","putative","quotidian",
    "sardonic","sartorial","scholastic","stochastic","surreptitious","tryst",
    "vacuous","venal","vivifying","voluble"
  ],

  // weight 2 - word-form groups; the card rotates through the forms
  groups: [
    ["comport","comports","comporting"],
    ["ascribe","ascribes"],
    ["foment","foments"],
    ["dialectic","dialectical"],
    ["pedagogue","pedagogical"],
    ["bloviating","bloviation"],
    ["vacillation","vacillates"],
    ["compunction","compunctions"],
    ["apoplectic","apoplexy"],
    ["perfidy","perfidiousness"],
    ["temerity","temerarious"],
    ["ostensible","ostensibly"],
    ["plaudit","plaudits"],
    ["recalcitrant","recalcitrance"],
    ["reticent","reticence"],
    ["proscribe","proscribed"],
    ["auspice","auspices","auspicious"],
    ["extoll","extolled"],
    ["exhortation","exhorting"],
    ["malcontent","malcontents"],
    ["notional","notionally"],
    ["contempt","contemptuous"],
    ["diametric","diametrically"],
    ["acquiesce","acquiescing"],
    ["portent","portend"],
    ["evidentiary","evidentially"],
    ["balk","balked"],
    ["reviled","reviling"],
    ["dispensation","dispensationalist"],
    ["accede","acceded"],
    ["prostrate","prostration"],
    ["eminent","eminently"],
    ["predation","predations"],
    ["excise","excision"],
    ["penury","penurious"],
    ["sophist","sophistry"],
    ["duplicity","duplicitous"],
    ["indolence","indolent"],
    ["epistemic","epistemology"]
  ],

  // no standard definition found - card shows the word + a search link
  noDef: ["composture","bordillo","plotism","scarfer","fraught-less","pluribus"]
},

/* ================ LIST 2: PEOPLE (SCIENCE) ================ */
{
  id: "pioneers",
  name: "Pioneers of Science",
  type: "wiki",
  items: [
    { name: "Enrico Fermi", titles: ["Enrico Fermi"] },
    { name: "John von Neumann", titles: ["John von Neumann"] },
    { name: "James Clerk Maxwell", titles: ["James Clerk Maxwell"] },
    { name: "Lord Kelvin", titles: ["William Thomson, 1st Baron Kelvin"] },
    { name: "J. Robert Oppenheimer", titles: ["J. Robert Oppenheimer"] },
    { name: "Edward Teller", titles: ["Edward Teller"] },
    { name: "Leo Szilard", titles: ["Leo Szilard"] },
    { name: "Stanislaw Ulam", titles: ["Stanislaw Ulam"] },
    { name: "Joseph Fourier", titles: ["Joseph Fourier"] },
    { name: "Erwin Schrodinger", titles: ["Erwin Schrödinger"] },
    { name: "Max Planck", titles: ["Max Planck"] },
    { name: "Hans Bethe", titles: ["Hans Bethe"] },
    { name: "Dmitri Mendeleev", titles: ["Dmitri Mendeleev"] },
    { name: "James Watt", titles: ["James Watt"] },
    { name: "Charles-Augustin de Coulomb", titles: ["Charles-Augustin de Coulomb"] },
    { name: "Thomas Young", titles: ["Thomas Young"] },
    { name: "Henri Poincare", titles: ["Henri Poincaré"] },
    { name: "Joseph-Louis Lagrange", titles: ["Joseph-Louis Lagrange"] },
    { name: "James Prescott Joule", titles: ["James Prescott Joule"] },
    { name: "William Shockley", titles: ["William Shockley"] },
    { name: "Alessandro Volta", titles: ["Alessandro Volta"] },
    { name: "Blaise Pascal", titles: ["Blaise Pascal"] },
    { name: "Theodore von Karman", titles: ["Theodore von Kármán"] },
    { name: "George Gabriel Stokes", titles: ["George Gabriel Stokes"] },
    { name: "Dennis Gabor", titles: ["Dennis Gabor"] },
    { name: "Claude-Louis Navier", titles: ["Claude-Louis Navier"] },
    { name: "Arnold Sommerfeld", titles: ["Arnold Sommerfeld"] },
    { name: "Osborne Reynolds", titles: ["Osborne Reynolds"] },
    { name: "Andre-Marie Ampere", titles: ["André-Marie Ampère"] },
    { name: "Georg Ohm", titles: ["Georg Ohm"] },
    { name: "Michael Faraday", titles: ["Michael Faraday"] },
    { name: "Oliver Heaviside", titles: ["Oliver Heaviside"] },
    { name: "J. J. Thomson", titles: ["J. J. Thomson"] },
    { name: "Albert A. Michelson", titles: ["Albert A. Michelson"] },
    { name: "Arthur Compton", titles: ["Arthur Compton"] },
    { name: "Ludwig Boltzmann", titles: ["Ludwig Boltzmann"] },
    { name: "Robert Hooke", titles: ["Robert Hooke"] },
    { name: "Joseph von Fraunhofer", titles: ["Joseph von Fraunhofer"] },
    { name: "Paul Dirac", titles: ["Paul Dirac"] },
    { name: "Satyendra Nath Bose", titles: ["Satyendra Nath Bose"] },
    { name: "Werner Heisenberg", titles: ["Werner Heisenberg"] },
    { name: "Wolfgang Pauli", titles: ["Wolfgang Pauli"] },
    { name: "Felix Bloch", titles: ["Felix Bloch"] },
    { name: "Edward Mills Purcell", titles: ["Edward Mills Purcell"] },
    { name: "Hendrik Lorentz", titles: ["Hendrik Lorentz"] },
    { name: "Charles H. Townes", titles: ["Charles H. Townes"] },
    { name: "Theodore Maiman", titles: ["Theodore Maiman"] },
    { name: "Hermann Minkowski", titles: ["Hermann Minkowski"] },
    { name: "Hermann von Helmholtz", titles: ["Hermann von Helmholtz"] },
    { name: "Guglielmo Marconi", titles: ["Guglielmo Marconi"] },
    { name: "George Boole", titles: ["George Boole"] },
    { name: "John Dalton", titles: ["John Dalton"] },
    { name: "Robert H. Goddard", titles: ["Robert H. Goddard"] },
    { name: "Pieter Zeeman", titles: ["Pieter Zeeman"] },
    { name: "Johannes van der Waals", titles: ["Johannes Diderik van der Waals"] },
    { name: "Rudolf Clausius", titles: ["Rudolf Clausius"] },
    { name: "William Rankine", titles: ["William John Macquorn Rankine"] },
    { name: "Charles Algernon Parsons", titles: ["Charles Algernon Parsons"] },
    { name: "Henry Cavendish", titles: ["Henry Cavendish"] },
    { name: "Ernest Rutherford", titles: ["Ernest Rutherford"] },
    { name: "Louis de Broglie", titles: ["Louis de Broglie"] },
    { name: "Ernest Lawrence", titles: ["Ernest Lawrence"] },
    { name: "Gerolamo Cardano", titles: ["Gerolamo Cardano"] },
    { name: "Charles Babbage", titles: ["Charles Babbage"] },
    { name: "Pierre de Fermat", titles: ["Pierre de Fermat"] },
    { name: "Augustin-Louis Cauchy", titles: ["Augustin-Louis Cauchy"] },
    { name: "Jean le Rond d'Alembert", titles: ["Jean le Rond d'Alembert"] },
    { name: "Denis Diderot", titles: ["Denis Diderot"] },
    { name: "Carl Friedrich Gauss", titles: ["Carl Friedrich Gauss"] },
    { name: "Christiaan Huygens", titles: ["Christiaan Huygens"] },
    { name: "George Green", titles: ["George Green (mathematician)"] },
    { name: "Claude Shannon", titles: ["Claude Shannon"] },
    { name: "Thomas Midgley Jr.", titles: ["Thomas Midgley Jr."] },
    { name: "Robert Edison Fulton Jr.", titles: ["Robert Edison Fulton Jr."] },
    { name: "Barre de Saint-Venant", titles: ["Adhémar Jean Claude Barré de Saint-Venant"] },
    { name: "Lev Pontryagin", titles: ["Lev Pontryagin"] },
    { name: "Evariste Galois", titles: ["Évariste Galois"] },
    { name: "Niels Henrik Abel", titles: ["Niels Henrik Abel"] }
  ]
},

/* ============== LIST 3: LAWS, EFFECTS & THEORY ============== */
{
  id: "laws",
  name: "Laws & Effects",
  type: "wiki",
  items: [
    { name: "Seebeck effect", titles: ["Thermoelectric effect"], formula: "V = -S\\,\\Delta T" },
    { name: "Permittivity", titles: ["Permittivity"], formula: "c = \\dfrac{1}{\\sqrt{\\mu_0 \\varepsilon_0}}" },
    { name: "Permeability", titles: ["Permeability (electromagnetism)"] },
    { name: "Gauss's Law", titles: ["Gauss's law"], formula: "\\oint \\vec{E}\\cdot d\\vec{A} = \\dfrac{Q_{\\text{enc}}}{\\varepsilon_0}" },
    { name: "Hooke's Law", titles: ["Hooke's law"], formula: "F = -k x" },
    { name: "Faraday's Law", titles: ["Faraday's law of induction"], formula: "\\varepsilon = -\\dfrac{d\\Phi_B}{dt}" },
    { name: "Lenz's Law", titles: ["Lenz's law"], formula: "\\varepsilon = -N\\dfrac{d\\Phi_B}{dt}" },
    { name: "Biot-Savart Law", titles: ["Biot–Savart law"], formula: "d\\vec{B} = \\dfrac{\\mu_0}{4\\pi}\\dfrac{I\\,d\\vec{\\ell}\\times\\hat{r}}{r^2}" },
    { name: "Stefan-Boltzmann Law", titles: ["Stefan–Boltzmann law"], formula: "j^{\\star} = \\sigma T^4" },
    { name: "Rydberg Formula", titles: ["Rydberg formula"], formula: "\\dfrac{1}{\\lambda} = R\\left(\\dfrac{1}{n_1^2}-\\dfrac{1}{n_2^2}\\right)" },
    { name: "Huygens-Fresnel Principle", titles: ["Huygens–Fresnel principle"] },
    { name: "Babinet's Principle", titles: ["Babinet's principle"] },
    { name: "Thin Lens Equation", titles: ["Thin lens"], formula: "\\dfrac{1}{f} = \\dfrac{1}{v} - \\dfrac{1}{u}" },
    { name: "Lensmaker's Equation", titles: ["Lens (optics)"], formula: "\\dfrac{1}{f} = (n-1)\\left(\\dfrac{1}{R_1}-\\dfrac{1}{R_2}\\right)" },
    { name: "Snell's Law", titles: ["Snell's law"], formula: "n_1 \\sin\\theta_1 = n_2 \\sin\\theta_2" },
    { name: "Fresnel Equations", titles: ["Fresnel equations"] },
    { name: "Brewster's Angle", titles: ["Brewster's angle"], formula: "\\tan\\theta_B = \\dfrac{n_2}{n_1}" },
    { name: "Bernoulli's Equation", titles: ["Bernoulli's principle"], formula: "P + \\tfrac{1}{2}\\rho v^2 + \\rho g h = \\text{const}" },
    { name: "Venturi Effect", titles: ["Venturi effect"] },
    { name: "Minkowski Spacetime", titles: ["Minkowski space"], formula: "ds^2 = -c^2dt^2 + dx^2 + dy^2 + dz^2" },
    { name: "Riemannian Manifold", titles: ["Riemannian manifold"] },
    { name: "Coriolis Effect", titles: ["Coriolis force"], formula: "\\vec{a}_C = -2\\,\\vec{\\Omega}\\times\\vec{v}" },
    { name: "Acousto-optic Effect", titles: ["Acousto-optic effect"] },
    { name: "Kerr & Pockels Effects", titles: ["Kerr effect", "Pockels effect"] },
    { name: "Piezoelectricity", titles: ["Piezoelectricity"] },
    { name: "Photoelasticity", titles: ["Photoelasticity"] },
    { name: "Ductile-Brittle Transition Temperature", titles: ["Ductile–brittle transition temperature"] },
    { name: "Newton's Laws of Motion", titles: ["Newton's laws of motion"], formula: "\\vec{F} = m\\vec{a}" },
    { name: "Euler's Laws of Motion", titles: ["Euler's laws of motion"] },
    { name: "Kepler's Laws", titles: ["Kepler's laws of planetary motion"], formula: "T^2 \\propto a^3" },
    { name: "Laws of Thermodynamics", titles: ["Laws of thermodynamics"] },
    { name: "Reynolds Number", titles: ["Reynolds number"], formula: "\\mathrm{Re} = \\dfrac{\\rho v L}{\\mu}" },
    { name: "Karman Vortex Street", titles: ["Kármán vortex street"] },
    { name: "Stern-Gerlach Experiment", titles: ["Stern–Gerlach experiment"] },
    { name: "Law of Definite Proportions", titles: ["Law of definite proportions"] },
    { name: "Conservation of Mass", titles: ["Conservation of mass"] },
    { name: "Law of Multiple Proportions", titles: ["Law of multiple proportions"] },
    { name: "Superposition Principle", titles: ["Superposition principle"] },
    { name: "Transmittance", titles: ["Transmittance"] },
    { name: "Boltzmann Constant", titles: ["Boltzmann constant"], formula: "k_B = 1.380649\\times10^{-23}\\ \\mathrm{J/K}" },
    { name: "Helmholtz Free Energy", titles: ["Helmholtz free energy"], formula: "F = U - TS" },
    { name: "Gibbs Free Energy", titles: ["Gibbs free energy"], formula: "G = H - TS" },
    { name: "Brownian Motion", titles: ["Brownian motion"] },
    { name: "Black-Body Radiation", titles: ["Black-body radiation"] },
    { name: "Hess's Law", titles: ["Hess's law"] },
    { name: "Ideal Gas Law", titles: ["Ideal gas law"], formula: "PV = nRT" },
    { name: "Van der Waals Equation", titles: ["Van der Waals equation"], formula: "\\left(P + \\dfrac{an^2}{V^2}\\right)(V - nb) = nRT" },
    { name: "Valence Bond Theory", titles: ["Valence bond theory"] },
    { name: "Equivalence Principle", titles: ["Equivalence principle"] },
    { name: "Special & General Relativity", titles: ["Special relativity", "General relativity"], formula: "E = mc^2,\\quad \\gamma = \\dfrac{1}{\\sqrt{1-v^2/c^2}}" },
    { name: "Emissivity", titles: ["Emissivity"], formula: "\\epsilon = \\dfrac{j}{j_{\\text{bb}}}" },
    { name: "Rankine Cycle", titles: ["Rankine cycle"], formula: "\\eta = \\dfrac{w_{\\text{net}}}{q_{\\text{in}}}" },
    { name: "Hall Effect", titles: ["Hall effect"], formula: "V_H = \\dfrac{IB}{nte}" },
    { name: "Magnetocaloric Effect", titles: ["Magnetic refrigeration"] },
    { name: "Laser Cooling", titles: ["Laser cooling"] },
    { name: "Doppler Effect (light)", titles: ["Relativistic Doppler effect"], formula: "f = f_0\\sqrt{\\dfrac{1+\\beta}{1-\\beta}}" },
    { name: "Joule-Thomson Effect", titles: ["Joule–Thomson effect"], formula: "\\mu_{JT} = \\left(\\dfrac{\\partial T}{\\partial P}\\right)_H" },
    { name: "Lambert's Cosine Law", titles: ["Lambert's cosine law"], formula: "I = I_0\\cos\\theta" },
    { name: "Laplace's Equation", titles: ["Laplace's equation"], formula: "\\nabla^2\\varphi = 0" },
    { name: "Poiseuille's Equation", titles: ["Hagen–Poiseuille equation"], formula: "Q = \\dfrac{\\pi r^4\\,\\Delta P}{8\\mu L}" },
    { name: "Caustic (optics)", titles: ["Caustic (optics)"] },
    { name: "Archimedes' Principle", titles: ["Archimedes' principle"], formula: "F_b = \\rho g V" },
    { name: "Pascal's Law", titles: ["Pascal's law"], formula: "\\Delta P = \\rho g\\,\\Delta h" },
    { name: "Fresnel Zone", titles: ["Fresnel zone"] },
    { name: "Lami's Theorem", titles: ["Lami's theorem"], formula: "\\dfrac{A}{\\sin\\alpha} = \\dfrac{B}{\\sin\\beta} = \\dfrac{C}{\\sin\\gamma}" },
    { name: "Buckingham Pi Theorem", titles: ["Buckingham π theorem"] },
    { name: "Boyle's / Charles's / Gay-Lussac's Laws", titles: ["Boyle's law", "Charles's law", "Gay-Lussac's law"], formula: "PV=\\text{const};\\quad \\tfrac{V}{T}=\\text{const};\\quad \\tfrac{P}{T}=\\text{const}" },
    { name: "Mass-Spring-Damper Model", titles: ["Harmonic oscillator"], formula: "m\\ddot{x} + c\\dot{x} + kx = 0" },
    { name: "Nash Embedding Theorems", titles: ["Nash embedding theorems"] },
    { name: "Clausius Theorem", titles: ["Clausius theorem"], formula: "\\oint \\dfrac{\\delta Q}{T} \\le 0" },
    { name: "Galvanic Corrosion", titles: ["Galvanic corrosion"] },
    { name: "Rayleigh's Equation", titles: ["Rayleigh–Plesset equation"] },
    { name: "Saint-Venant's Principle / Torsion", titles: ["Saint-Venant's principle", "Torsion (mechanics)"] },
    { name: "Shallow Water Equations", titles: ["Shallow water equations"] },
    { name: "Coulomb Friction", titles: ["Friction"], formula: "F \\le \\mu N" },
    { name: "Mersenne's Laws", titles: ["Mersenne's laws"], formula: "f = \\dfrac{1}{2L}\\sqrt{\\dfrac{T}{\\mu}}" },
    { name: "Le Chatelier's Principle", titles: ["Le Chatelier's principle"] },
    { name: "Triboelectric Effect", titles: ["Triboelectric effect"] },
    { name: "Kelvin-Voigt & Maxwell Models", titles: ["Kelvin–Voigt material", "Maxwell material"] },
    { name: "Resonant Scattering", titles: ["Resonance fluorescence"] },
    { name: "Rayleigh Scattering", titles: ["Rayleigh scattering"], formula: "I \\propto \\dfrac{1}{\\lambda^4}" },
    { name: "Low-Pass Filtering", titles: ["Low-pass filter"], formula: "f_c = \\dfrac{1}{2\\pi RC}" },
    { name: "Lumped-Element Model", titles: ["Lumped-element model"] },
    { name: "Leidenfrost Effect", titles: ["Leidenfrost effect"] },
    { name: "Meissner Effect", titles: ["Meissner effect"] },
    { name: "London Equations", titles: ["London equations"], formula: "\\nabla^2\\vec{B} = \\dfrac{\\vec{B}}{\\lambda_L^2}" },
    { name: "Spin-Stabilized Magnetic Levitation", titles: ["Spin-stabilized magnetic levitation"] },
    { name: "Earnshaw's Theorem", titles: ["Earnshaw's theorem"] },
    { name: "Maxwell's Equations", titles: ["Maxwell's equations"] },
    { name: "BCS Theory", titles: ["BCS theory"] }
  ]
},

/* ============= LIST 4: MACHINES & MECHANISMS ============= */
{
  id: "machines",
  name: "Machines & Mechanisms",
  type: "wiki",
  items: [
    { name: "Inverter", titles: ["Power inverter"] },
    { name: "Rectifier", titles: ["Rectifier"] },
    { name: "Dynamo", titles: ["Dynamo"] },
    { name: "Solenoid", titles: ["Solenoid"] },
    { name: "Potentiometer", titles: ["Potentiometer"] },
    { name: "Engine", titles: ["Engine"] },
    { name: "Electric Motor", titles: ["Electric motor"] },
    { name: "Turbine", titles: ["Turbine"] },
    { name: "Electric Generator", titles: ["Electric generator"] },
    { name: "Diode", titles: ["Diode"] },
    { name: "Transistor", titles: ["Transistor"] },
    { name: "Vacuum Tube", titles: ["Vacuum tube"] },
    { name: "Induction Coil", titles: ["Induction coil"] },
    { name: "Capacitor", titles: ["Capacitor"], formula: "C = \\dfrac{Q}{V}" },
    { name: "Squirrel-Cage Rotor", titles: ["Squirrel-cage rotor"] },
    { name: "Induction Motor", titles: ["Induction motor"] },
    { name: "Ratchet & Pawl", titles: ["Ratchet (device)"] },
    { name: "Oil Metering Pump", titles: ["Metering pump"] },
    { name: "Rack & Pinion", titles: ["Rack and pinion"] },
    { name: "Jackshaft", titles: ["Jackshaft"] },
    { name: "Carburetor", titles: ["Carburetor"] },
    { name: "Alternator", titles: ["Alternator"] },
    { name: "Impeller", titles: ["Impeller"] },
    { name: "Commutator", titles: ["Commutator (electric)"] },
    { name: "Turbocharger", titles: ["Turbocharger"] },
    { name: "Desmodromic Valve", titles: ["Desmodromic valve"] },
    { name: "Inductor", titles: ["Inductor"], formula: "V = L\\dfrac{dI}{dt}" },
    { name: "Fresnel Lens", titles: ["Fresnel lens"] },
    { name: "Band-Pass Filter", titles: ["Band-pass filter"] },
    { name: "Helmholtz Resonator", titles: ["Helmholtz resonance"], formula: "f = \\dfrac{c}{2\\pi}\\sqrt{\\dfrac{A}{V L}}" },
    { name: "Magnetic Yoke", titles: ["Yoke (electrical)"] },
    { name: "Arc Converter", titles: ["Arc converter"] },
    { name: "Cyclotron", titles: ["Cyclotron"], formula: "f = \\dfrac{qB}{2\\pi m}" },
    { name: "Coherer", titles: ["Coherer"] },
    { name: "Monopole & Dipole Antennas", titles: ["Monopole antenna", "Dipole antenna"] },
    { name: "Magneto", titles: ["Ignition magneto"] },
    { name: "Attenuator", titles: ["Attenuator (electronics)"] },
    { name: "Acousto-Optic Modulator", titles: ["Acousto-optic modulator"] },
    { name: "Transducer", titles: ["Transducer"] },
    { name: "Kerr Cell", titles: ["Kerr effect"] },
    { name: "Constant-Velocity Joint", titles: ["Constant-velocity joint"] },
    { name: "Cardan Joint", titles: ["Universal joint"] },
    { name: "Afterburner", titles: ["Afterburner"] },
    { name: "Pelton Wheel", titles: ["Pelton wheel"] },
    { name: "Choke & Throttle", titles: ["Choke valve", "Throttle"] },
    { name: "Linear Motor", titles: ["Linear motor"] },
    { name: "Comparator", titles: ["Comparator"] },
    { name: "Heat Exchanger & Intercooler", titles: ["Heat exchanger", "Intercooler"] },
    { name: "Supercharger", titles: ["Supercharger"] },
    { name: "Geneva Drive", titles: ["Geneva drive"] },
    { name: "Gear Types", titles: ["Gear"] },
    { name: "Fusion Confinement (Stellarator / Z-Pinch / Magnetic Mirror / Tokamak)", titles: ["Stellarator", "Z-pinch", "Magnetic mirror", "Tokamak"] },
    { name: "Corliss Steam Engine", titles: ["Corliss steam engine"] },
    { name: "Gimbal & Gyroscope", titles: ["Gimbal", "Gyroscope"] },
    { name: "Gerotor Pump", titles: ["Gerotor"] },
    { name: "Resolver", titles: ["Resolver (electrical)"] },
    { name: "Thermocouple & Thermopile", titles: ["Thermocouple", "Thermopile"] },
    { name: "Bimetallic Strip", titles: ["Bimetallic strip"] },
    { name: "Thermistor", titles: ["Thermistor"] },
    { name: "De Laval Nozzle", titles: ["De Laval nozzle"] },
    { name: "Expansion Chamber", titles: ["Expansion chamber"] },
    { name: "Antikythera Mechanism", titles: ["Antikythera mechanism"] },
    { name: "Orrery", titles: ["Orrery"] },
    { name: "Teller-Ulam Design", titles: ["Teller–Ulam design"] },
    { name: "Molecular Sieve", titles: ["Molecular sieve"] },
    { name: "Pantograph", titles: ["Pantograph"] },
    { name: "Fulton Skyhook", titles: ["Fulton surface-to-air recovery system"] },
    { name: "Wankel Rotary Engine", titles: ["Wankel engine"] },
    { name: "Napier Deltic", titles: ["Napier Deltic"] },
    { name: "Leyden Jar", titles: ["Leyden jar"] },
    { name: "Turbojet", titles: ["Turbojet"] },
    { name: "Turbofan", titles: ["Turbofan"] }
  ]
}

];
